import Lottie from 'lottie-react'
import lottieYogaDeveloper from '../public/lotties/animation-developer-yoga.json'

import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>jinShine 블로그</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Lottie
          animationData={lottieYogaDeveloper}
          loop={true}
          style={{ width: 500, height: 500 }}></Lottie>
      </main>
      <footer></footer>
    </>
  )
}

export default Home
