import { ReactNode } from 'react'
import Header from './Header'
import Footer from './Footer'
import Head from 'next/head'

type LayoutProps = {
  children: ReactNode
}

export default function Layout(props: LayoutProps) {
  return (
    <>
      <Head>
        <title>jinShine 블로그</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <>{props.children}</>
      <Footer></Footer>
    </>
  )
}
